#!/bin/bash
#
#
#
#
clear
echo "Please provide your domain name without the www. (e.g. livechat.mydomain.com or mydomain.com/livechat)"
read -p "Type your domain name, then press [ENTER] : " MY_DOMAIN
echo "Please provide a name for the Live Chat DATABASE"
read -p "Type your database name, then press [ENTER] : " dbname
echo "Please provide a DATABASE username"
read -p "Type your database username, then press [ENTER] : " dbuser
echo "Please provide a database root password"
read -p "Root Passwrod [ENTER] : " ROOT_PWD
clear
read -t 30 -p "Thank you. Please press [ENTER] continue or [Control]+[C] to cancel"

#Add repository for BCMATH
sudo echo "deb http://security.ubuntu.com/ubuntu artful-security main universe"  | sudo tee -a /etc/apt/sources.list
sudo apt-get update && sudo apt-get upgrade -y
apt install php-fpm php-mysql php-xml php-mbstring php-common php-curl php-gd php-zip php-soap php-bcmath unzip phpenmod mbstring  -y

# ADD TO NGINX SERVER BLOCK
# --- for domain.com/chat---
# location SPEC_URL {
#    try_files $uri $uri/ /SPEC_URL/index.php?q=$uri&$args;
# }
#
# -- for chat.domain.com---
#
#
#

sudo service nginx reload
sudo service nginx restart

userpass=$(openssl rand -base64 29 | tr -d "=+/" | cut -c1-25)
echo "CREATE DATABASE $dbname;" | sudo mysql -u root -p$ROOT_PWD
echo "CREATE USER '$dbuser'@'localhost' IDENTIFIED BY '$userpass';" | sudo mysql -u root -p$ROOT_PWD
echo "GRANT ALL PRIVILEGES ON $dbname.* TO '$dbuser'@'localhost';" | sudo mysql -u root -p$ROOT_PWD
echo "FLUSH PRIVILEGES;" | sudo mysql -u root -p$ROOT_PWD
echo "delete from mysql.user where user='mysql';" | sudo mysql -u root -p$ROOT_PWD

wget https://github.com/remdex/livehelperchat/archive/master.zip
unzip ./master.zip
mkdir /var/www/html/$MY_DOMAIN
cp -a ./livehelperchat-master/lhc_web/. /var/www/html/$MY_DOMAIN
chown -R www-data:www-data /var/www/html/$MY_DOMAIN
chmod -R 777 /var/www/html/$MY_DOMAIN/cache
chmod -R 777 /var/www/html/$MY_DOMAIN/settings/settings.ini.default.php
chmod -R 777 /var/www/html/$MY_DOMAIN/var/storage
chmod -R 777 /var/www/html/$MY_DOMAIN/var/userphoto
clear
echo
echo "Here are your database details!"
echo
echo "Database Name: $dbname"
echo "Username: $dbuser"
echo "Password: $userpass"
echo
echo
